# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Clear all exes
        run: |
          rm ./*.exe
          
      # Runs a single command using the runners shell
      - name: Write Last Updated
        run: |
          echo "Last Fetched on:" > LastUpdated.txt
          date >> LastUpdated.txt
      - name: Download
        uses: schmiddim/action-wget-unzip@v2
        with:
          # URL of the file to download
          url: https://download.sysinternals.com/files/PSTools.zip
          # New filename to rename the downloaded file
          destination: .
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ">=16.x.x"
      - name: TODO - Check for file changes and make tag
        run: "echo not implemented"
      - name: Commit
        run: |
          git config --global user.email "pstools-mirror[bot]"
          git config --global user.name "PSTools Mirror / BOT"
          git add .
          git commit -m "Update PSUtils"
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
